

name: Linux Build

on: push

jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: 8ae87a91f06f49559f0db387bc2bd1ea01419880

    - name: Install deps
      run: |
        sudo apt-get install libxtst-dev libpng++-dev
    - name: Install node gyp
      run: |
        npm install -g node-gyp
    - name: Build
      run: |
        node-gyp rebuild
