

name: Linux Build

on: push

jobs:
  build:
    name: Build on Ubuntu
    runs-on: windows-2019
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: 8ae87a91f06f49559f0db387bc2bd1ea01419880
    - name: Set up Node.js 14
      uses: actions/setup-node@v3
      with:
        node-version: 14
    - name: Set up Python 2.7
      uses: actions/setup-python@v4
      with:
          python-version: '2.7'
    - name: Install deps
      run: |
        sudo apt-get install xorg-dev
        sudo apt-get install -y libxtst-dev libpng++-dev python2 python-is-python2 gcc
    - name: Install node gyp
      run: |
        npm install -g node-gyp
    - name: Build
      run: |
        node-gyp rebuild
